#server settings
server:
  port: 9001
  context-path:

logging:
  config: classpath:log4j2.yaml

spring:
    redis:
       cache:
             clusterNodes: 127.0.0.1:6379
             commandTimeout: 5000
