#server settings
server:
  port: 9004
  context-path:

spring:
  elasticsearch:
    jest:
      uris: http://127.0.0.1:10086,http://127.0.0.1:10087
      read-timeout: 20000 #读取超时
      connection-timeout: 20000 #连接超时






