#server settings
server:
  port: 12601
  context-path: /mybatis


spring:
    datasource:
        #DruidDataSource 所需参数
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/jeetc
        username: root
        password: root
        initialSize: 3
        minIdle: 3
        maxActive: 30
        maxWait: 15000
        timeBetweenEvictionRunsMillis: 120000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        removeAbandoned: true
        removeAbandonedTimeoutMillis: 20000
        logAbandoned: true
        logDifferentThread: true
        filters: log4j2
        connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000
        useGlobalDataSourceStat: true
        # Druid 监控 Servlet 配置参数
        druidRegistrationUrl: /druid/*
        resetEnable: true
        loginUsername: 监控后台登录名称
        loginPassword: 监控后台登录密码
        # Druid 监控过滤相关配置参数
        filtersUrlPatterns: /*
        exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'
        sessionStatMaxCount: 2000
        sessionStatEnable: true
        principalSessionName: session_user_key
        profileEnable: true

mybatis:
    config-location: classpath:/mybatis-config.xml
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.fexo.bean



logging:
  config: classpath:log4j2.yaml
